development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgrestest_user
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgrestest_user
  password: password

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
